name: Terraform Deployment with Go Tests
on:
  push:
    branches:
      - master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'
    - name: Run Go tests
      run: |
        if [ -f go.mod ]; then
          go test ./... -v
        else
          echo "No Go modules found, skipping tests."
        fi
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 'latest'
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -var "render_api_key=${{ secrets.RENDER_API_KEY }}" -var "render_owner_id=${{ secrets.RENDER_OWNER_ID }}"
    - name: Terraform Apply
      run: |
        terraform apply -auto-approve -var "render_api_key=${{ secrets.RENDER_API_KEY }}" -var "render_owner_id=${{ secrets.RENDER_OWNER_ID }}"
